[camera]
image-dimensions = [400, 400]
position = [0.0, 2.5, 6.0]
rotation = { type = "euler", roll = -0.1, pitch = 0.0, yaw = 0.0 }
fov = 45.0
background-color = [0.7, 0.8, 0.9]

[[materials]]
type = "diffuse"
albedo = [0.5, 0.5, 0.5]

[[materials]]
type = "diffuse"
albedo = [1.0, 0.0, 0.0]

[[objects]]
material = 0
shape = { type = "quad", q = [-5.0, 0.0, -5.0], u = [10.0, 0.0, 0.0], v = [0.0, 0.0, 10.0] }

[[objects]]
material = 1
shape = { type = "prism", origin = [0.0, 0.0, 0.0], width = 1.0, height = 2.0, depth = 1.0, rotation = { type = "euler", roll = 0.0, pitch = 3.926990, yaw = 0.0 } }